### ISSUE TITLE
Please make JMXBean annotation inheritable

### ISSUE THREAD

**Issue by technocoreai** [uklimaschewski/JMXWrapper#10]
Currently, the `@JMXBean` annotation isn't marked as inheritable, so it must be repeated on every single child class. Is there any point in not marking the annotation as `@Inheritable`?

**Comment by uklimaschewski** [comment]
I added it to the `JMXBean` interface [here](https://github.com/uklimaschewski/JMXWrapper/blob/ff90bef48f6d0d490d5b4f194e830e4b03d3af99/src/com/udojava/jmx/wrapper/JMXBean.java#L42). I also added a [test case](https://github.com/uklimaschewski/JMXWrapper/blob/ff90bef48f6d0d490d5b4f194e830e4b03d3af99/tests/com/udojava/jmx/wrapper/InheritanceTest.java). Please let me know, if that solves your problem.

**Comment by technocoreai** [comment]
Looks great, thanks! Any chance of a Maven Central release including that?

**Comment by uklimaschewski** [comment]
Done, see issue #11 - it may take a day or two until it pops up in maven central.

**Comment by technocoreai** [comment]
Great, thanks again.

**Comment by uklimaschewski** [comment]
No problem, Sonatype was fast, version 1.3 is now available on Maven Central.
