### ISSUE TITLE
Include LICENSE.txt in binary

### ISSUE THREAD

**Issue by phansson** [uklimaschewski/JMXWrapper#13]
The MIT license states that

> The above copyright notice and this permission notice shall be
> included in all copies or substantial portions of the Software.

Which means that for us using your library, the full `LICENSE.txt` (yours) needs to be available in what we distribute, not just a generic reference to the MIT license.

Something like this in the POM should do the job:

```
<resources>
    <resource>
        <directory>${basedir}</directory>
        <targetPath>META-INF</targetPath>
        <includes>
            <include>LICENSE.txt</include>
        </includes>
    </resource>
</resources>

```

**Comment by uklimaschewski** [comment]
OK, I will add this.

**Comment by uklimaschewski** [comment]
The license is now in release 1.4: https://github.com/uklimaschewski/JMXWrapper/releases/tag/1.4
