### ISSUE TITLE
Maven finds POM of v1.2 broken

### ISSUE THREAD

**Issue by dcsordas** [uklimaschewski/JMXWrapper#8]
hi,

when trying to build project within maven with jmxwrapper 1.2 as a dependency, I get this error:

The POM for com.udojava:jmxwrapper:jar:1.2 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model
Non-parseable POM /Users/dcsordas/.m2/repository/com/udojava/jmxwrapper/1.2/jmxwrapper-1.2.pom: expected = after attribute name (position: TEXT seen ...meta name="selected-link" value="repo_source" data-pjax-transient>... @32:72)  @ line 32, column 72

and build breaks on jmxwrapper symbols
downgrading jmxwrapper dependency to 1.1 results in a nice project build

could you please look into this?

**Comment by uklimaschewski** [comment]
Are you trying to build jmxwrapper using maven, or are you linking it with a dependency to your project?

**Comment by dcsordas** [comment]
I'm using it as a dependency

**Comment by uklimaschewski** [comment]
Finally, I managed to get my linux box running with my new wifi, so I set up a test project and have no problems using the repo.

For the test project, I am using the following `pom.xml`. Maybe you should check yours for possible errors:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.udojava.tests</groupId>
  <artifactId>maventest</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>maventest</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <repositories>
     <repository>
        <id>uklimaschewski-maven-repo</id>
        <name>Maven repository from uklimaschewski on GitHub</name>
        <url>https://raw.github.com/uklimaschewski/maven-repo/master</url>
        <layout>default</layout>
     </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.udojava</groupId>
      <artifactId>jmxwrapper</artifactId>
      <version>1.2</version>
    </dependency>
  </dependencies>
</project>

```

Here's a snipped of the log, to show that it is downloaded:
```text
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/uk/maventest/src/main/resources
Downloading: https://raw.github.com/uklimaschewski/maven-repo/master/com/udojava/jmxwrapper/1.2/jmxwrapper-1.2.pom
642b downloaded  (jmxwrapper-1.2.pom)
Downloading: https://raw.github.com/uklimaschewski/maven-repo/master/com/udojava/jmxwrapper/1.2/jmxwrapper-1.2.jar
14K downloaded  (jmxwrapper-1.2.jar)
```
